### ISSUE TITLE
relayRawSocket是否考虑改用pcap实现

### ISSUE THREAD

**Issue by neteroster** [linhua55/some_kcptun_tools#1]
这样可以利用winpcap，原生Windows即可执行。

**Comment by linhua55** [comment]
这个优先级不高，我是在Windows下的Archlinux虚拟机中运行的，自己在Windows下是必开Linux虚拟机的。如果觉得虚拟机重的话，docker应该也可以

**Comment by neteroster** [comment]
好的 感谢建议。

**Comment by ccsexyz** [comment]
@lizongzeshunshun 如果想在 windows 下使用的话可以看一下 https://github.com/ccsexyz/kcptun

**Comment by neteroster** [comment]
@ccsexyz 谢谢。
